.TH urlopen 1 "7 January 2018" "Version 2.0.0"

.SH NAME
urlopen \- a tool for opening windows' internet shortcut files

.SH SYNOPSIS
.B urlopen
[
.I FILENAME
]

.SH DESCRIPTION
Open the url file in the default browser.

.SH AUTHOR
Written by Matt Gaikema.

.SH REPORTING BUGS
Open an issue at <https://github.com/TexAgg/urlopen/issues>.